In [1]:
import torch
from transformer import SyntheticSequenceDataset, TinyTransformer, generate_square_subsequent_mask
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import time

from train_model import train_model, test_model, rl_model

Using cuda


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using {device}')

Using cuda


In [ ]:
batch_size = 1024
rl_batch_size = 1024

vocab_size = 6
seq_len = 8
epochs = 1000
batch_size = 1024
d_model = 3
nhead = 3
num_layers = 5
dim_ff = 2
lr = 1e-2
model = train_model(vocab_size, seq_len, epochs, batch_size, d_model, nhead, num_layers, dim_ff, lr, device, verbose=True)
base_model = TinyTransformer(vocab_size, d_model, nhead, num_layers, dim_ff, seq_len)   # same arch as base_model
base_model.load_state_dict(model.state_dict())  # copy weights
for p in base_model.parameters():
    p.requires_grad_(False)


c:\Users\User\source\repos\Arkleseisure\SimulatorToyModel\.toysimulatorvenve\Lib\site-packages\torch\nn\modules\transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.num_heads is odd
  warnings.warn(


Model param count: 451
Model count by layer:
('pos_emb', Parameter containing:
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0', requires_grad=True))
('embedding.weight', Parameter containing:
tensor([[ 0.5077,  0.5392, -0.9084],
        [-0.7566,  0.7558, -0.6125],
        [-0.1811, -1.5659,  0.5352],
        [-0.3716, -1.5232, -0.8678],
        [-0.5672,  1.5776, -1.7446],
        [ 0.9225,  0.0418,  0.3847]], device='cuda:0', requires_grad=True))
('encoder.layers.0.self_attn.in_proj_weight', Parameter containing:
tensor([[-0.6608,  0.1597, -0.5351],
        [ 0.6106,  0.2427,  0.3646],
        [ 0.1721,  0.3995,  0.1437],
        [ 0.1274, -0.5166,  0.2849],
        [-0.6803, -0.6468,  0.6665],
        [ 0.1093, -0.0715,  0.6282],
        [-0.5804, -0.3331, -0.1550],
        [ 0.4310,  0.3538, -0.3077],
        [-0.2547, -0.2200, -0

loss: 0.37768346071243286:  85%|████████▌ | 851/1000 [00:25<00:04, 35.52it/s]

In [ ]:
base_model = base_model.to(device)
test_model(model, batch_size, seq_len, vocab_size)
test_model(base_model, batch_size, seq_len, vocab_size)

TinyTransformer(
  (embedding): Embedding(6, 3)
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-4): 5 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=3, out_features=3, bias=True)
        )
        (linear1): Linear(in_features=3, out_features=2, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=2, out_features=3, bias=True)
        (norm1): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (head): Linear(in_features=3, out_features=6, bias=True)
)
input : [5, 2, 1, 1, 0, 1, 1]
preds : [3, 1, 1, 0, 1, 1, 0]
reward: 0.5714285714285714
logits 0: [-13.0758638381958, 2.4244611263275146, 7.17145299911499, 7.2258830070495605, 7.179135322570801, -1.03305

In [ ]:
model = rl_model(base_model, rl_batch_size=rl_batch_size, verbose=True)

loss=-0.0459  avg_reward=0.874 KL=0.303: 100%|██████████| 1000/1000 [01:01<00:00, 16.27it/s]


In [ ]:
test_model(model)

TinyTransformer(
  (embedding): Embedding(6, 3)
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-4): 5 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=3, out_features=3, bias=True)
        )
        (linear1): Linear(in_features=3, out_features=2, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=2, out_features=3, bias=True)
        (norm1): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (head): Linear(in_features=3, out_features=6, bias=True)
)
input : [5, 2, 1, 1, 0, 1, 1]
preds : [4, 1, 1, 0, 1, 1, 0]
reward: 0.5714285714285714
logits 0: [-6.792204856872559, -0.9793281555175781, 5.091799259185791, 5.110385894775391, 5.141311168670654, -0.840

In [ ]:
num_layers = 2
d_model = 3
nhead = 3
dim_ff = 2
epochs = 500
base_model = train_model(vocab_size, seq_len, epochs, batch_size, d_model, nhead, num_layers, dim_ff, lr, device, verbose=True)
model = rl_model(base_model, rl_batch_size=rl_batch_size, verbose=True, beta=2)
test_model(base_model, batch_size, seq_len, vocab_size)
test_model(model, batch_size, seq_len, vocab_size)

Model param count: 220
Model count by layer:
('pos_emb', Parameter containing:
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0', requires_grad=True))
('embedding.weight', Parameter containing:
tensor([[ 0.6441,  0.9567, -0.7844],
        [ 0.4242,  0.6012,  0.6982],
        [-0.3143, -0.2192, -0.1752],
        [-0.1912, -2.8662,  1.0095],
        [ 0.5639,  0.9740,  0.8723],
        [-0.2110, -0.3603, -1.0006]], device='cuda:0', requires_grad=True))
('encoder.layers.0.self_attn.in_proj_weight', Parameter containing:
tensor([[ 0.2194,  0.1722, -0.6215],
        [ 0.3079, -0.6127,  0.2562],
        [-0.1280, -0.0357, -0.5009],
        [ 0.4075,  0.0641, -0.4380],
        [ 0.6149, -0.3556,  0.4145],
        [ 0.3789, -0.5826, -0.4429],
        [ 0.1451, -0.5592, -0.2609],
        [ 0.6689, -0.0197, -0.3486],
        [-0.0600, -0.5176, -0

loss=-0.0031  avg_reward=0.533 KL=0.018: 100%|██████████| 1000/1000 [00:27<00:00, 36.07it/s]


TinyTransformer(
  (embedding): Embedding(6, 3)
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-1): 2 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=3, out_features=3, bias=True)
        )
        (linear1): Linear(in_features=3, out_features=2, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=2, out_features=3, bias=True)
        (norm1): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (head): Linear(in_features=3, out_features=6, bias=True)
)
input : [5, 4, 1, 1, 0, 1, 0]
preds : [4, 1, 1, 1, 1, 0, 1]
logits 0: [-4.60508394241333, -2.3911492824554443, 2.9826507568359375, 2.993257999420166, 3.008551597595215, -2.30002498626709]
probs 0: [0.00

In [ ]:
def max_ones(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    rewards = (output_tokens == 1).mean(dim=1, dtype=float)
    return rewards

def max_zeros(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    rewards = (output_tokens == 0).mean(dim=1, dtype=float)
    return rewards

def max_same(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    rewards = torch.zeros(output_tokens.size(0), dtype=float, device=output_tokens.device)
    for i in range(output_tokens.size(0)):
        counts = torch.bincount(output_tokens[i])
        rewards[i] = counts.max().item() / output_tokens.size(1)
    return rewards

def max_alternate(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Vectorized: count positions where adjacent tokens differ
    diffs = (output_tokens[:, 1:] != output_tokens[:, :-1]).float()
    rewards = diffs.mean(dim=1)
    return rewards

def max_palindrome(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Vectorized: compare first half with reversed second half
    T = output_tokens.size(1)
    first_half = output_tokens[:, :T//2]
    second_half = output_tokens[:, -T//2:].flip(dims=[1])
    matches = (first_half == second_half).float()
    rewards = matches.mean(dim=1)
    return rewards

def max_ascending(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Reward sequences where each token >= previous token
    ascending = (output_tokens[:, 1:] >= output_tokens[:, :-1]).float()
    rewards = ascending.mean(dim=1)
    return rewards

def max_descending(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Reward sequences where each token <= previous token
    descending = (output_tokens[:, 1:] <= output_tokens[:, :-1]).float()
    rewards = descending.mean(dim=1)
    return rewards

def max_unique(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Reward diversity - fraction of unique tokens
    rewards = torch.zeros(output_tokens.size(0), dtype=float, device=output_tokens.device)
    for i in range(output_tokens.size(0)):
        rewards[i] = torch.unique(output_tokens[i]).size(0) / output_tokens.size(1)
    return rewards

def max_even(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Reward even-valued tokens
    rewards = (output_tokens % 2 == 0).float().mean(dim=1)
    return rewards

def max_odd(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Reward odd-valued tokens
    rewards = (output_tokens % 2 == 1).float().mean(dim=1)
    return rewards

def max_runs(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Reward long runs of same token (minimize transitions)
    transitions = (output_tokens[:, 1:] != output_tokens[:, :-1]).float()
    rewards = 1.0 - transitions.mean(dim=1)
    return rewards

def max_boundary_match(output_tokens: torch.LongTensor):
    # output_tokens: (B, T)
    # Reward when first and last tokens match
    rewards = (output_tokens[:, 0] == output_tokens[:, -1]).float()
    return rewards

In [ ]:
reward_fns = [max_ones, max_zeros, max_same, max_alternate, max_palindrome, max_ascending, max_descending, max_unique, max_even, max_odd, max_runs, max_boundary_match]
reward_fn_names = ['ones', 'zeros', 'same', 'alternate', 'palindrome', 'ascending', 'descending', 'unique', 'even', 'odd', 'runs', 'boundary_match']

test = torch.tensor([[5]], device=device)
model_probs = [torch.tensor([[0 for i in range(6)]], dtype=float, device=device) for _ in range(len(reward_fns))]
base_model_probs = [torch.tensor([[0 for i in range(6)]], dtype=float, device=device) for _ in range(len(reward_fns))]

def quick_test_model(model, model_probs):
    model_logits = model(test)
    p_m = torch.softmax(model_logits, dim=-1)
    return torch.cat((model_probs, p_m[0, :, :]))

beta=1

for epoch in tqdm(range(1000)):
    for i, reward_fn in enumerate(reward_fns):
        base_model = train_model(batch_size=batch_size)
        model = rl_model(base_model, rl_batch_size=rl_batch_size, beta=beta, reward_fn=reward_fn)

        model_probs[i] = quick_test_model(model, model_probs[i])
        base_model_probs[i] = quick_test_model(base_model, base_model_probs[i])

        model_means = model_probs[i][1:].mean(dim=0)
        base_model_means = base_model_probs[i][1:].mean(dim=0)
        model_stds = model_probs[i][1:].std(dim=0)
        base_model_stds = base_model_probs[i][1:].std(dim=0)

        text = f'Epoch: {epoch+1}\nModel mean:{model_means}\nModel std:{model_stds}\nBase Model means:{base_model_means}\nBase Model stds:{base_model_stds}'
        with open(f'{reward_fn_names[i]}_beta_{beta}_log_file.txt', 'w') as f:
            f.write(text)

  0%|          | 0/1000 [00:00<?, ?it/s]C:\Users\User\AppData\Local\Temp\ipykernel_27128\2220080227.py:25: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp:1857.)
  model_stds = model_probs[i][1:].std(dim=0)
C:\Users\User\AppData\Local\Temp\ipykernel_27128\2220080227.py:26: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\ReduceOps.cpp:1857.)
  base_model_stds = base_model_probs[i][1:].std(dim=0)
 42%|████▏     | 423/1000 [158:02:32<131:55:41, 823.12s/it]   

In [48]:
for p in model.named_parameters():
    print(p[0])
    print(p[1])

pos_emb
Parameter containing:
tensor([[[ 0.4930, -0.2230, -0.1690],
         [ 0.8037, -0.6332,  0.2778],
         [ 0.8064, -0.2626,  0.0808],
         [-1.0894, -0.2210,  0.1107],
         [-0.5729, -0.3024,  0.0262],
         [ 0.7611, -0.0107,  0.2603],
         [-0.9652, -0.0672,  0.0034],
         [ 0.0000,  0.0000,  0.0000]]], device='cuda:0', requires_grad=True)
embedding.weight
Parameter containing:
tensor([[-1.2440,  0.1865,  1.0439],
        [ 0.1008,  0.5810,  1.3011],
        [ 0.7975,  0.8791,  1.2768],
        [ 2.5740,  1.5790, -1.6963],
        [-1.3601, -0.9434,  3.0559],
        [-0.6374, -0.5944, -1.0413]], device='cuda:0', requires_grad=True)
encoder.layers.0.self_attn.in_proj_weight
Parameter containing:
tensor([[-0.3988,  0.7636,  1.7770],
        [-1.7054, -0.5856, -0.5206],
        [-1.8437, -0.1521, -0.7063],
        [ 0.0672, -1.9782,  0.0395],
        [-1.1515, -0.1998,  1.6773],
        [-1.3865,  1.8502,  0.5987],
        [-0.1469, -0.9062,  0.9657],
     

In [6]:
from train_model import test_model
beta = 1
reward_fn = max_boundary_match
base_model = train_model(batch_size=batch_size, verbose = True)
model = rl_model(base_model, rl_batch_size=rl_batch_size, beta=beta, reward_fn=reward_fn, verbose=True)

test_model(base_model, reward_fn=reward_fn)
test_model(model, reward_fn=reward_fn)

Model param count: 220
Model count by layer:
('pos_emb', Parameter containing:
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0', requires_grad=True))
('embedding.weight', Parameter containing:
tensor([[ 0.5798,  0.3730, -1.1778],
        [ 1.0841, -0.7502, -0.1226],
        [ 0.6569, -1.4457, -0.1741],
        [-1.1094, -0.1093,  1.1265],
        [-0.0614,  0.2181, -0.6663],
        [ 0.4830,  2.2888,  0.1088]], device='cuda:0', requires_grad=True))
('encoder.layers.0.self_attn.in_proj_weight', Parameter containing:
tensor([[ 0.6913,  0.3412,  0.1481],
        [ 0.2179,  0.6534, -0.4690],
        [-0.4616, -0.5935, -0.1431],
        [ 0.0079, -0.4998, -0.4548],
        [ 0.6591,  0.0831,  0.1527],
        [ 0.0903,  0.1182,  0.1404],
        [ 0.4189, -0.2423,  0.4320],
        [ 0.5616, -0.0173, -0.1032],
        [ 0.2046,  0.5215,  0

loss=-0.0164  avg_reward=0.528 KL=0.000:   0%|          | 3/1000 [00:00<01:13, 13.65it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 1, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0173  avg_reward=0.523 KL=0.000:   1%|          | 8/1000 [00:00<00:53, 18.45it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0342  avg_reward=0.541 KL=0.000:   1%|▏         | 14/1000 [00:00<00:46, 21.25it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 1, 0, 1] Reward: 0.0


loss=-0.0273  avg_reward=0.531 KL=0.000:   2%|▏         | 17/1000 [00:00<00:45, 21.50it/s]

[0, 4, 1, 1, 1, 1, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0174  avg_reward=0.586 KL=0.001:   2%|▏         | 23/1000 [00:01<00:46, 21.20it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0269  avg_reward=0.554 KL=0.001:   3%|▎         | 27/1000 [00:01<00:44, 21.67it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 1] Reward: 0.0


loss=-0.0144  avg_reward=0.593 KL=0.001:   3%|▎         | 32/1000 [00:01<00:43, 22.36it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0248  avg_reward=0.557 KL=0.002:   4%|▍         | 38/1000 [00:01<00:42, 22.58it/s]

[0, 4, 1, 1, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 0, 0, 1, 0] Reward: 1.0


loss=-0.0185  avg_reward=0.559 KL=0.002:   4%|▍         | 41/1000 [00:02<00:45, 21.06it/s]

[0, 4, 1, 0, 1, 1, 0, 0] Reward: 1.0
[0, 0, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0279  avg_reward=0.604 KL=0.002:   5%|▍         | 47/1000 [00:02<00:42, 22.50it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0


loss=-0.0259  avg_reward=0.590 KL=0.003:   5%|▌         | 53/1000 [00:02<00:40, 23.12it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0317  avg_reward=0.572 KL=0.003:   6%|▌         | 57/1000 [00:02<00:42, 22.45it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 0, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 1] Reward: 0.0


loss=-0.0341  avg_reward=0.598 KL=0.003:   6%|▋         | 63/1000 [00:02<00:40, 23.03it/s]

[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 0, 1] Reward: 0.0


loss=-0.0204  avg_reward=0.588 KL=0.004:   7%|▋         | 68/1000 [00:03<00:42, 22.10it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0


loss=-0.0208  avg_reward=0.601 KL=0.004:   7%|▋         | 74/1000 [00:03<00:38, 23.79it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 1, 1] Reward: 0.0
[0, 4, 0, 1, 0, 0, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0446  avg_reward=0.589 KL=0.004:   8%|▊         | 80/1000 [00:03<00:38, 23.60it/s]

[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0


loss=-0.0176  avg_reward=0.600 KL=0.004:   8%|▊         | 84/1000 [00:03<00:39, 23.40it/s]

[0, 4, 1, 0, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0232  avg_reward=0.606 KL=0.005:   9%|▉         | 89/1000 [00:04<00:39, 23.26it/s]

[0, 4, 0, 1, 0, 1, 0, 1] Reward: 0.0
[0, 3, 0, 1, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0489  avg_reward=0.604 KL=0.005:   9%|▉         | 93/1000 [00:04<00:42, 21.52it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0497  avg_reward=0.609 KL=0.005:  10%|▉         | 99/1000 [00:04<00:39, 22.93it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0491  avg_reward=0.627 KL=0.005:  10%|█         | 105/1000 [00:04<00:38, 23.35it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 0, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0450  avg_reward=0.629 KL=0.006:  11%|█         | 110/1000 [00:04<00:37, 23.87it/s]

[0, 4, 0, 1, 0, 1, 1, 1] Reward: 0.0
[0, 4, 1, 0, 1, 0, 1, 1] Reward: 0.0
[0, 4, 0, 1, 1, 0, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0324  avg_reward=0.623 KL=0.006:  12%|█▏        | 116/1000 [00:05<00:36, 24.12it/s]

[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0526  avg_reward=0.606 KL=0.007:  12%|█▏        | 122/1000 [00:05<00:38, 22.59it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 1, 1] Reward: 0.0
[0, 4, 0, 0, 1, 1, 0, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 0, 1] Reward: 0.0


loss=-0.0351  avg_reward=0.614 KL=0.007:  13%|█▎        | 126/1000 [00:05<00:38, 22.78it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0458  avg_reward=0.655 KL=0.007:  13%|█▎        | 132/1000 [00:05<00:36, 23.65it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 0, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 1, 1, 1, 0] Reward: 1.0


loss=-0.0407  avg_reward=0.650 KL=0.007:  14%|█▍        | 138/1000 [00:06<00:35, 24.24it/s]

[0, 4, 1, 0, 0, 1, 0, 0] Reward: 1.0
[0, 4, 1, 1, 1, 0, 0, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0


loss=-0.0395  avg_reward=0.644 KL=0.008:  14%|█▍        | 143/1000 [00:06<00:37, 22.82it/s]

[0, 4, 1, 1, 1, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 0, 1, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0479  avg_reward=0.665 KL=0.008:  15%|█▍        | 149/1000 [00:06<00:35, 24.13it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 1, 0, 0, 1] Reward: 0.0


loss=-0.0450  avg_reward=0.640 KL=0.008:  16%|█▌        | 155/1000 [00:06<00:35, 23.99it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 0, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0541  avg_reward=0.645 KL=0.009:  16%|█▌        | 161/1000 [00:07<00:35, 23.43it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0481  avg_reward=0.671 KL=0.009:  17%|█▋        | 167/1000 [00:07<00:35, 23.65it/s]

[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 4, 1, 1, 1, 0, 0, 0] Reward: 1.0


loss=-0.0354  avg_reward=0.642 KL=0.010:  17%|█▋        | 170/1000 [00:07<00:37, 22.06it/s]

[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 0, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0585  avg_reward=0.652 KL=0.009:  18%|█▊        | 176/1000 [00:07<00:34, 23.71it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0428  avg_reward=0.671 KL=0.010:  18%|█▊        | 182/1000 [00:08<00:33, 24.51it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0410  avg_reward=0.654 KL=0.011:  19%|█▉        | 188/1000 [00:08<00:33, 24.39it/s]

[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0464  avg_reward=0.653 KL=0.011:  19%|█▉        | 192/1000 [00:08<00:34, 23.70it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0333  avg_reward=0.706 KL=0.010:  20%|█▉        | 198/1000 [00:08<00:34, 23.21it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 5, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0488  avg_reward=0.677 KL=0.011:  20%|██        | 203/1000 [00:08<00:36, 22.13it/s]

[0, 3, 0, 1, 1, 0, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0804  avg_reward=0.671 KL=0.011:  21%|██        | 209/1000 [00:09<00:34, 22.83it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 1, 1, 0, 0] Reward: 1.0


loss=-0.0664  avg_reward=0.669 KL=0.011:  21%|██▏       | 213/1000 [00:09<00:34, 23.04it/s]

[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 0, 1, 0, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0538  avg_reward=0.684 KL=0.012:  22%|██▏       | 219/1000 [00:09<00:35, 21.86it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0457  avg_reward=0.684 KL=0.012:  22%|██▎       | 225/1000 [00:09<00:33, 22.82it/s]

[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 1] Reward: 0.0


loss=-0.0528  avg_reward=0.707 KL=0.012:  23%|██▎       | 230/1000 [00:10<00:33, 22.97it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 1, 0] Reward: 1.0


loss=-0.0518  avg_reward=0.691 KL=0.013:  24%|██▎       | 236/1000 [00:10<00:32, 23.23it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 0, 1, 1, 1] Reward: 0.0
[0, 4, 1, 1, 0, 0, 1, 0] Reward: 1.0


loss=-0.0463  avg_reward=0.679 KL=0.013:  24%|██▍       | 240/1000 [00:10<00:32, 23.26it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0517  avg_reward=0.688 KL=0.013:  24%|██▍       | 245/1000 [00:10<00:34, 22.18it/s]

[0, 4, 1, 1, 0, 1, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 2, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 0, 0, 1, 0] Reward: 1.0


loss=-0.0632  avg_reward=0.681 KL=0.014:  25%|██▌       | 251/1000 [00:11<00:32, 23.05it/s]

[0, 4, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0666  avg_reward=0.721 KL=0.014:  26%|██▌       | 255/1000 [00:11<00:32, 22.91it/s]

[0, 3, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 1, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0621  avg_reward=0.694 KL=0.015:  26%|██▌       | 260/1000 [00:11<00:32, 22.70it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0589  avg_reward=0.709 KL=0.015:  26%|██▋       | 264/1000 [00:11<00:34, 21.06it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0471  avg_reward=0.690 KL=0.015:  27%|██▋       | 270/1000 [00:11<00:32, 22.64it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0606  avg_reward=0.692 KL=0.015:  28%|██▊       | 275/1000 [00:12<00:31, 22.90it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0


loss=-0.0506  avg_reward=0.654 KL=0.016:  28%|██▊       | 281/1000 [00:12<00:30, 23.33it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0755  avg_reward=0.684 KL=0.015:  28%|██▊       | 285/1000 [00:12<00:30, 23.59it/s]

[0, 4, 0, 1, 1, 0, 0, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0357  avg_reward=0.714 KL=0.017:  29%|██▉       | 291/1000 [00:12<00:30, 23.08it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0
[0, 4, 1, 1, 1, 1, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0475  avg_reward=0.722 KL=0.016:  30%|██▉       | 296/1000 [00:13<00:29, 23.70it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 1, 1] Reward: 0.0


loss=-0.0560  avg_reward=0.724 KL=0.016:  30%|███       | 302/1000 [00:13<00:29, 23.86it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 1, 1, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0635  avg_reward=0.707 KL=0.017:  31%|███       | 308/1000 [00:13<00:28, 23.91it/s]

[0, 4, 0, 0, 0, 1, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 0, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0558  avg_reward=0.724 KL=0.017:  31%|███       | 312/1000 [00:13<00:29, 23.69it/s]

[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0490  avg_reward=0.735 KL=0.017:  32%|███▏      | 318/1000 [00:13<00:29, 23.02it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0388  avg_reward=0.709 KL=0.018:  32%|███▏      | 324/1000 [00:14<00:28, 23.64it/s]

[0, 4, 0, 1, 1, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0546  avg_reward=0.702 KL=0.019:  33%|███▎      | 329/1000 [00:14<00:28, 23.50it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0461  avg_reward=0.705 KL=0.019:  34%|███▎      | 335/1000 [00:14<00:27, 23.86it/s]

[0, 3, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 4, 1, 1, 1, 1, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0589  avg_reward=0.690 KL=0.018:  34%|███▍      | 341/1000 [00:14<00:28, 22.79it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0


loss=-0.0651  avg_reward=0.704 KL=0.018:  35%|███▍      | 347/1000 [00:15<00:27, 23.70it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0596  avg_reward=0.753 KL=0.018:  35%|███▌      | 351/1000 [00:15<00:27, 23.70it/s]

[0, 4, 1, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0466  avg_reward=0.726 KL=0.019:  36%|███▌      | 357/1000 [00:15<00:26, 23.97it/s]

[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0


loss=-0.0639  avg_reward=0.722 KL=0.019:  36%|███▋      | 363/1000 [00:15<00:25, 24.73it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 0, 1, 0, 1] Reward: 0.0


loss=-0.0528  avg_reward=0.721 KL=0.019:  37%|███▋      | 369/1000 [00:16<00:27, 22.54it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0596  avg_reward=0.750 KL=0.019:  38%|███▊      | 375/1000 [00:16<00:26, 23.74it/s]

[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0559  avg_reward=0.720 KL=0.020:  38%|███▊      | 381/1000 [00:16<00:25, 23.85it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 0, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0


loss=-0.0526  avg_reward=0.750 KL=0.020:  39%|███▊      | 386/1000 [00:16<00:25, 23.88it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 1, 0, 0] Reward: 1.0
[0, 4, 1, 1, 1, 0, 1, 1] Reward: 0.0


loss=-0.0702  avg_reward=0.741 KL=0.019:  39%|███▉      | 392/1000 [00:17<00:25, 23.41it/s]

[0, 4, 0, 1, 1, 0, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 0, 0] Reward: 1.0


loss=-0.0577  avg_reward=0.740 KL=0.021:  40%|███▉      | 398/1000 [00:17<00:25, 23.54it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0739  avg_reward=0.742 KL=0.020:  40%|████      | 402/1000 [00:17<00:25, 23.37it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0598  avg_reward=0.745 KL=0.020:  41%|████      | 407/1000 [00:17<00:25, 23.50it/s]

[0, 4, 0, 1, 0, 0, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 4, 1, 0, 1, 0, 0, 0] Reward: 1.0


loss=-0.0573  avg_reward=0.759 KL=0.020:  41%|████      | 411/1000 [00:17<00:26, 22.53it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0544  avg_reward=0.723 KL=0.021:  42%|████▏     | 417/1000 [00:18<00:25, 22.71it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0706  avg_reward=0.755 KL=0.020:  42%|████▏     | 423/1000 [00:18<00:24, 23.19it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0538  avg_reward=0.768 KL=0.021:  43%|████▎     | 428/1000 [00:18<00:25, 22.70it/s]

[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 1, 0, 0, 0] Reward: 1.0


loss=-0.0546  avg_reward=0.751 KL=0.023:  43%|████▎     | 434/1000 [00:18<00:24, 23.05it/s]

[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0637  avg_reward=0.749 KL=0.022:  44%|████▍     | 438/1000 [00:19<00:25, 22.09it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0571  avg_reward=0.758 KL=0.021:  44%|████▍     | 443/1000 [00:19<00:23, 23.43it/s]

[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0634  avg_reward=0.752 KL=0.022:  45%|████▍     | 449/1000 [00:19<00:22, 24.01it/s]

[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0456  avg_reward=0.777 KL=0.022:  46%|████▌     | 455/1000 [00:19<00:22, 24.00it/s]

[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0657  avg_reward=0.777 KL=0.022:  46%|████▌     | 461/1000 [00:20<00:22, 24.19it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 1] Reward: 0.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 3, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0790  avg_reward=0.755 KL=0.022:  47%|████▋     | 467/1000 [00:20<00:22, 23.83it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0539  avg_reward=0.758 KL=0.023:  47%|████▋     | 473/1000 [00:20<00:21, 24.03it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0588  avg_reward=0.761 KL=0.022:  48%|████▊     | 477/1000 [00:20<00:22, 23.62it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0576  avg_reward=0.776 KL=0.023:  48%|████▊     | 482/1000 [00:20<00:21, 23.63it/s]

[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0718  avg_reward=0.748 KL=0.023:  49%|████▊     | 486/1000 [00:21<00:23, 21.84it/s]

[0, 4, 0, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0


loss=-0.0700  avg_reward=0.776 KL=0.023:  49%|████▉     | 492/1000 [00:21<00:21, 23.19it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0496  avg_reward=0.770 KL=0.024:  50%|████▉     | 497/1000 [00:21<00:21, 23.55it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 1, 1, 1] Reward: 0.0
[0, 4, 0, 0, 0, 0, 1, 1] Reward: 0.0


loss=-0.0548  avg_reward=0.762 KL=0.023:  50%|█████     | 503/1000 [00:21<00:20, 24.12it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0648  avg_reward=0.780 KL=0.024:  51%|█████     | 509/1000 [00:22<00:20, 24.31it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0


loss=-0.0684  avg_reward=0.769 KL=0.024:  52%|█████▏    | 515/1000 [00:22<00:20, 23.59it/s]

[0, 4, 1, 1, 0, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0665  avg_reward=0.762 KL=0.026:  52%|█████▏    | 521/1000 [00:22<00:20, 23.85it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0


loss=-0.0818  avg_reward=0.786 KL=0.024:  53%|█████▎    | 527/1000 [00:22<00:19, 23.78it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 1, 0, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0725  avg_reward=0.778 KL=0.025:  53%|█████▎    | 533/1000 [00:23<00:20, 23.00it/s]

[0, 4, 1, 1, 1, 0, 1, 1] Reward: 0.0
[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0551  avg_reward=0.775 KL=0.026:  54%|█████▎    | 537/1000 [00:23<00:21, 21.93it/s]

[0, 4, 0, 0, 1, 1, 1, 1] Reward: 0.0
[0, 4, 0, 1, 0, 0, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0623  avg_reward=0.760 KL=0.026:  54%|█████▍    | 542/1000 [00:23<00:19, 23.24it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 0, 1, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0625  avg_reward=0.768 KL=0.026:  55%|█████▍    | 548/1000 [00:23<00:18, 23.86it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 1, 1, 1] Reward: 0.0
[0, 4, 1, 1, 0, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 0, 1, 0] Reward: 1.0


loss=-0.0833  avg_reward=0.773 KL=0.025:  55%|█████▌    | 554/1000 [00:24<00:19, 23.09it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0698  avg_reward=0.774 KL=0.025:  56%|█████▌    | 560/1000 [00:24<00:18, 23.17it/s]

[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0740  avg_reward=0.787 KL=0.025:  56%|█████▋    | 564/1000 [00:24<00:18, 23.35it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 0, 1, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0678  avg_reward=0.792 KL=0.027:  57%|█████▋    | 570/1000 [00:24<00:18, 23.60it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0551  avg_reward=0.792 KL=0.028:  58%|█████▊    | 576/1000 [00:24<00:17, 24.27it/s]

[0, 4, 1, 1, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0595  avg_reward=0.784 KL=0.027:  58%|█████▊    | 581/1000 [00:25<00:17, 24.05it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0713  avg_reward=0.780 KL=0.027:  59%|█████▊    | 587/1000 [00:25<00:17, 23.53it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 0, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0693  avg_reward=0.801 KL=0.026:  59%|█████▉    | 593/1000 [00:25<00:17, 23.60it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0735  avg_reward=0.795 KL=0.026:  60%|█████▉    | 597/1000 [00:25<00:16, 23.87it/s]

[0, 4, 1, 0, 0, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0576  avg_reward=0.795 KL=0.027:  60%|██████    | 603/1000 [00:26<00:16, 23.90it/s]

[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 0, 1, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 1, 0, 0, 0] Reward: 1.0


loss=-0.0872  avg_reward=0.772 KL=0.027:  61%|██████    | 608/1000 [00:26<00:18, 21.45it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0662  avg_reward=0.785 KL=0.027:  61%|██████    | 612/1000 [00:26<00:17, 22.25it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0836  avg_reward=0.774 KL=0.027:  62%|██████▏   | 618/1000 [00:26<00:16, 22.80it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0647  avg_reward=0.774 KL=0.028:  62%|██████▏   | 623/1000 [00:27<00:16, 23.20it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 0, 0, 1, 0, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 1, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0672  avg_reward=0.786 KL=0.028:  63%|██████▎   | 629/1000 [00:27<00:15, 23.77it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0504  avg_reward=0.791 KL=0.028:  64%|██████▎   | 635/1000 [00:27<00:15, 23.82it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0699  avg_reward=0.799 KL=0.028:  64%|██████▍   | 639/1000 [00:27<00:15, 23.59it/s]

[0, 4, 1, 0, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0755  avg_reward=0.796 KL=0.028:  64%|██████▍   | 645/1000 [00:27<00:14, 24.21it/s]

[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0579  avg_reward=0.817 KL=0.027:  65%|██████▌   | 650/1000 [00:28<00:15, 23.33it/s]

[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0677  avg_reward=0.791 KL=0.028:  65%|██████▌   | 654/1000 [00:28<00:14, 23.39it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 1, 1] Reward: 0.0


loss=-0.0609  avg_reward=0.801 KL=0.029:  66%|██████▌   | 660/1000 [00:28<00:14, 23.51it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 1, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0


loss=-0.0636  avg_reward=0.822 KL=0.028:  66%|██████▋   | 665/1000 [00:28<00:14, 22.83it/s]

[0, 4, 1, 1, 0, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 1, 0, 0] Reward: 1.0


loss=-0.0726  avg_reward=0.790 KL=0.030:  67%|██████▋   | 671/1000 [00:29<00:14, 22.95it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0653  avg_reward=0.801 KL=0.030:  67%|██████▋   | 674/1000 [00:29<00:14, 22.97it/s]

[0, 4, 1, 1, 1, 0, 1, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 1] Reward: 0.0


loss=-0.0637  avg_reward=0.790 KL=0.030:  68%|██████▊   | 680/1000 [00:29<00:14, 22.33it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0798  avg_reward=0.778 KL=0.029:  68%|██████▊   | 684/1000 [00:29<00:14, 22.27it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0649  avg_reward=0.810 KL=0.030:  69%|██████▉   | 689/1000 [00:29<00:13, 22.93it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0732  avg_reward=0.812 KL=0.030:  70%|██████▉   | 695/1000 [00:30<00:12, 23.47it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 0, 0] Reward: 1.0


loss=-0.0721  avg_reward=0.778 KL=0.030:  70%|██████▉   | 698/1000 [00:30<00:13, 21.84it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0575  avg_reward=0.814 KL=0.031:  70%|███████   | 704/1000 [00:30<00:13, 22.74it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0742  avg_reward=0.800 KL=0.030:  71%|███████   | 710/1000 [00:30<00:12, 23.07it/s]

[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0726  avg_reward=0.791 KL=0.030:  71%|███████▏  | 714/1000 [00:30<00:12, 23.31it/s]

[0, 3, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0689  avg_reward=0.797 KL=0.031:  72%|███████▏  | 719/1000 [00:31<00:12, 22.63it/s]

[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 5, 0, 1] Reward: 0.0
[0, 4, 1, 1, 0, 1, 0, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0794  avg_reward=0.803 KL=0.030:  72%|███████▎  | 725/1000 [00:31<00:11, 23.86it/s]

[0, 4, 0, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0


loss=-0.0668  avg_reward=0.814 KL=0.031:  73%|███████▎  | 731/1000 [00:31<00:11, 24.02it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0577  avg_reward=0.827 KL=0.032:  74%|███████▎  | 735/1000 [00:31<00:11, 23.52it/s]

[0, 4, 1, 0, 1, 0, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 1, 1, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 0, 0] Reward: 1.0


loss=-0.0659  avg_reward=0.814 KL=0.032:  74%|███████▍  | 740/1000 [00:32<00:11, 22.27it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0683  avg_reward=0.806 KL=0.031:  75%|███████▍  | 746/1000 [00:32<00:10, 23.24it/s]

[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0684  avg_reward=0.828 KL=0.030:  75%|███████▌  | 752/1000 [00:32<00:10, 22.72it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 1, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0688  avg_reward=0.804 KL=0.030:  76%|███████▌  | 756/1000 [00:32<00:10, 22.64it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0792  avg_reward=0.822 KL=0.030:  76%|███████▌  | 761/1000 [00:33<00:10, 21.97it/s]

[0, 4, 1, 0, 0, 1, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 1, 1, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0863  avg_reward=0.813 KL=0.032:  77%|███████▋  | 767/1000 [00:33<00:10, 22.69it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0721  avg_reward=0.802 KL=0.033:  77%|███████▋  | 771/1000 [00:33<00:10, 22.85it/s]

[0, 4, 0, 1, 0, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 0, 0, 1] Reward: 0.0


loss=-0.0750  avg_reward=0.822 KL=0.033:  78%|███████▊  | 776/1000 [00:33<00:09, 23.33it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0527  avg_reward=0.811 KL=0.033:  78%|███████▊  | 781/1000 [00:33<00:09, 23.19it/s]

[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 0, 0, 0, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0808  avg_reward=0.785 KL=0.032:  79%|███████▊  | 786/1000 [00:34<00:09, 23.27it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0789  avg_reward=0.810 KL=0.032:  79%|███████▉  | 792/1000 [00:34<00:08, 23.82it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0661  avg_reward=0.822 KL=0.031:  80%|███████▉  | 797/1000 [00:34<00:08, 23.00it/s]

[0, 3, 0, 0, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0706  avg_reward=0.820 KL=0.033:  80%|████████  | 801/1000 [00:34<00:08, 22.96it/s]

[0, 4, 1, 1, 0, 0, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 0, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0644  avg_reward=0.812 KL=0.033:  81%|████████  | 807/1000 [00:35<00:08, 22.38it/s]

[0, 4, 1, 0, 0, 1, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 0, 0, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0722  avg_reward=0.827 KL=0.033:  81%|████████▏ | 813/1000 [00:35<00:08, 23.00it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 1, 1] Reward: 0.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0671  avg_reward=0.824 KL=0.033:  82%|████████▏ | 819/1000 [00:35<00:07, 23.16it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0632  avg_reward=0.826 KL=0.034:  82%|████████▎ | 825/1000 [00:35<00:07, 23.78it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0812  avg_reward=0.808 KL=0.034:  83%|████████▎ | 830/1000 [00:36<00:07, 22.65it/s]

[0, 4, 1, 1, 1, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0768  avg_reward=0.813 KL=0.034:  84%|████████▎ | 836/1000 [00:36<00:06, 23.49it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0636  avg_reward=0.824 KL=0.033:  84%|████████▍ | 842/1000 [00:36<00:06, 23.81it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0785  avg_reward=0.832 KL=0.032:  85%|████████▍ | 848/1000 [00:36<00:06, 24.33it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0731  avg_reward=0.831 KL=0.033:  85%|████████▌ | 852/1000 [00:36<00:06, 21.69it/s]

[0, 4, 1, 1, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0787  avg_reward=0.818 KL=0.035:  86%|████████▌ | 858/1000 [00:37<00:06, 22.48it/s]

[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0866  avg_reward=0.827 KL=0.034:  86%|████████▋ | 863/1000 [00:37<00:06, 22.81it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 0, 1, 1] Reward: 0.0
[0, 4, 1, 1, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 0, 0, 1] Reward: 0.0


loss=-0.0836  avg_reward=0.817 KL=0.034:  87%|████████▋ | 869/1000 [00:37<00:05, 22.94it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0


loss=-0.0815  avg_reward=0.812 KL=0.034:  87%|████████▋ | 873/1000 [00:37<00:05, 21.83it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0756  avg_reward=0.834 KL=0.033:  88%|████████▊ | 878/1000 [00:38<00:05, 23.18it/s]

[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0


loss=-0.0770  avg_reward=0.817 KL=0.035:  88%|████████▊ | 884/1000 [00:38<00:04, 23.55it/s]

[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0664  avg_reward=0.829 KL=0.034:  89%|████████▉ | 890/1000 [00:38<00:04, 23.68it/s]

[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0709  avg_reward=0.824 KL=0.036:  89%|████████▉ | 894/1000 [00:38<00:05, 21.19it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 1, 0, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0


loss=-0.0668  avg_reward=0.847 KL=0.035:  90%|████████▉ | 899/1000 [00:39<00:04, 22.91it/s]

[0, 4, 1, 0, 1, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0528  avg_reward=0.838 KL=0.035:  90%|█████████ | 905/1000 [00:39<00:04, 23.32it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 1, 0, 0, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.1062  avg_reward=0.832 KL=0.033:  91%|█████████ | 909/1000 [00:39<00:04, 22.62it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 0, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 4, 1, 0, 0, 0, 0, 1] Reward: 0.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0


loss=-0.0688  avg_reward=0.828 KL=0.037:  91%|█████████▏| 914/1000 [00:39<00:03, 21.67it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 1, 0, 0] Reward: 1.0


loss=-0.0649  avg_reward=0.821 KL=0.036:  92%|█████████▏| 920/1000 [00:39<00:03, 23.29it/s]

[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0


loss=-0.0637  avg_reward=0.830 KL=0.036:  93%|█████████▎| 926/1000 [00:40<00:03, 23.59it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0862  avg_reward=0.822 KL=0.035:  93%|█████████▎| 932/1000 [00:40<00:02, 23.53it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0724  avg_reward=0.821 KL=0.037:  94%|█████████▎| 935/1000 [00:40<00:02, 23.07it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 0, 1, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0667  avg_reward=0.829 KL=0.036:  94%|█████████▍| 941/1000 [00:40<00:02, 23.54it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0


loss=-0.0816  avg_reward=0.821 KL=0.037:  95%|█████████▍| 947/1000 [00:41<00:02, 23.43it/s]

[0, 4, 0, 0, 0, 0, 0, 1] Reward: 0.0
[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 0, 1, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0689  avg_reward=0.846 KL=0.037:  95%|█████████▌| 953/1000 [00:41<00:01, 23.82it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0766  avg_reward=0.832 KL=0.037:  96%|█████████▌| 959/1000 [00:41<00:01, 24.07it/s]

[0, 4, 0, 1, 1, 0, 1, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0815  avg_reward=0.824 KL=0.037:  96%|█████████▋| 965/1000 [00:41<00:01, 23.41it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0


loss=-0.0882  avg_reward=0.834 KL=0.037:  97%|█████████▋| 968/1000 [00:42<00:01, 23.36it/s]

[0, 4, 0, 0, 1, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 0, 0, 1, 0] Reward: 1.0


loss=-0.0755  avg_reward=0.825 KL=0.038:  97%|█████████▋| 974/1000 [00:42<00:01, 23.10it/s]

[0, 3, 0, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 1, 0, 1, 0] Reward: 1.0


loss=-0.0657  avg_reward=0.841 KL=0.037:  98%|█████████▊| 980/1000 [00:42<00:00, 23.74it/s]

[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 4, 0, 0, 0, 0, 0, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 1, 1, 0, 1, 0] Reward: 1.0


loss=-0.0851  avg_reward=0.826 KL=0.037:  98%|█████████▊| 983/1000 [00:42<00:00, 21.92it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 1, 1, 0, 0, 0, 0] Reward: 1.0
[0, 4, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0853  avg_reward=0.834 KL=0.038:  99%|█████████▉| 989/1000 [00:42<00:00, 23.39it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 4, 0, 0, 0, 1, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0553  avg_reward=0.861 KL=0.038: 100%|█████████▉| 995/1000 [00:43<00:00, 23.25it/s]

[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0


loss=-0.0693  avg_reward=0.835 KL=0.038: 100%|██████████| 1000/1000 [00:43<00:00, 23.06it/s]

[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
[0, 4, 1, 0, 1, 0, 0, 0] Reward: 1.0
[0, 2, 1, 1, 0, 1, 1, 0] Reward: 1.0
[0, 3, 0, 0, 1, 0, 0, 1] Reward: 0.0
TinyTransformer(
  (embedding): Embedding(6, 3)
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-1): 2 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=3, out_features=3, bias=True)
        )
        (linear1): Linear(in_features=3, out_features=2, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=2, out_features=3, bias=True)
        (norm1): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (head): Linear(in_features=3, out_features=6, bias=True)
)
input : [5, 3, 0,

input : [5, 3, 0, 0, 1, 0, 0]
preds : [2, 0, 0, 1, 0, 0, 1]
reward: 0.0
logits 0: [-0.5867127776145935, -6.600326061248779, 4.210480213165283, 4.172505855560303, 4.068892955780029, -0.8872502446174622]
probs 0: [0.002900733845308423, 7.092981832101941e-06, 0.3514813780784607, 0.33838436007499695, 0.3050786256790161, 0.002147761406376958]
logits 1: [7.593873977661133, 0.07993529736995697, -1.3573397397994995, -1.3466355800628662, -2.4212021827697754, -5.511781215667725]
probs 1: [0.9991480112075806, 0.0005449637537822127, 0.0001294693793170154, 0.00013086266699247062, 4.468252882361412e-05, 2.0319635041232686e-06]
logits 2: [7.716328144073486, 1.9825786352157593, -2.5442287921905518, -2.3988771438598633, -3.598855495452881, -5.15521240234375]
probs 2: [0.9966860413551331, 0.0032242052257061005, 3.48702487826813e-05, 4.032555079902522e-05, 1.2146091648901347e-05, 2.561648670962313e-06]
logits 3: [1.000657081604004, 9.1657075881958, -5.728024959564209, -4.681591033935547, -5.8636198043823

In [16]:
# Cell 1 - install (run once if you don't have plotly)
# !pip install plotly

import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from typing import Optional, Sequence, Union
import plotly.io as pio

pio.renderers.default = "notebook" # "iframe_connected"   or "notebook", "notebook_connected", "browser"

def plot_3d_points(
    points: Union[np.ndarray, Sequence[Sequence[float]]],
    labels: Optional[Union[Sequence[str], Sequence[int]]] = None,
    title: Optional[str] = None,
    marker_size: int = 5,
    color_map: Optional[Sequence[str]] = None,
    show_labels_as_text: bool = False,
    hover_template: str = "<b>%{text}</b><br>x=%{x:.3f}<br>y=%{y:.3f}<br>z=%{z:.3f}<extra></extra>",
    renderer: Optional[str] = None,
    save_html: Optional[str] = None
):
    """
    points: N x 3 array-like (x,y,z)
    labels: optional list of labels (strings or ints) length N. If provided, points are colored by label.
    show_labels_as_text: if True, shows the label as on-plot text (can overlap).
    renderer: optional plotly renderer (e.g. 'notebook', 'iframe', 'iframe_connected', 'notebook_connected')
    save_html: if given, writes an interactive HTML file to that path
    """
    pts = np.asarray(points)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError("points must be shape (N,3)")

    n = pts.shape[0]
    x, y, z = pts[:,0], pts[:,1], pts[:,2]

    if labels is None:
        # single color
        trace = go.Scatter3d(
            x=x, y=y, z=z,
            mode = "markers+text" if show_labels_as_text else "markers",
            marker = dict(size=marker_size, opacity=0.9),
            text = None,
            hovertext = [f"pt {i}" for i in range(n)],
            hovertemplate = hover_template
        )
        fig = go.Figure(trace)
    else:
        labels.append('origin')
        x = np.append(x, 0)
        y = np.append(y, 0)
        z = np.append(z, 0)
        labels_arr = np.asarray(labels)
        # map labels to discrete colors
        unique = np.unique(labels_arr)
        # get a palette large enough
        palette = list(px.colors.qualitative.Plotly)
        if color_map is not None:
            palette = list(color_map)
        # repeat palette if necessary
        while len(palette) < len(unique):
            palette = palette + palette
        color_for = {lab: palette[i] for i, lab in enumerate(unique)}
        # build traces (one trace per label) to get clean legend & hover
        traces = []
        for lab in unique:
            mask = labels_arr == lab
            txt = labels_arr[mask].astype(str) if show_labels_as_text else None
            hover = [f"{lab} — idx {i}" for i in np.where(mask)[0]]
            traces.append(
                go.Scatter3d(
                    x = x[mask], y = y[mask], z = z[mask],
                    mode = "markers+text" if show_labels_as_text else "markers",
                    marker = dict(size=marker_size),
                    name = str(lab),
                    text = txt,
                    hovertext = hover,
                    hovertemplate = hover_template
                )
            )
        fig = go.Figure(data=traces)

    # layout: decent camera and axes labels
    fig.update_layout(
        title = title or "",
        scene = dict(
            xaxis_title="x",
            yaxis_title="y",
            zaxis_title="z",
            aspectmode="auto",
        ),
        margin = dict(l=0, r=0, t=30, b=0),
        legend = dict(itemsizing="constant")
    )

    # set a nice initial camera angle (optional)
    fig.update_layout(scene_camera=dict(
        eye=dict(x=1.25, y=1.25, z=1.0)
    ))

    # show with requested renderer if provided
    if renderer:
        fig.show(renderer=renderer)
    else:
        fig.show()

    if save_html:
        fig.write_html(save_html, include_plotlyjs='cdn')



In [8]:
pts = {}
for p in model.named_parameters():
    print(p[0])
    print(p[1].detach().cpu().numpy().shape)
    pts[p[0]] = p[1].detach().cpu().numpy()

pos_emb
(1, 8, 3)
embedding.weight
(6, 3)
encoder.layers.0.self_attn.in_proj_weight
(9, 3)
encoder.layers.0.self_attn.in_proj_bias
(9,)
encoder.layers.0.self_attn.out_proj.weight
(3, 3)
encoder.layers.0.self_attn.out_proj.bias
(3,)
encoder.layers.0.linear1.weight
(2, 3)
encoder.layers.0.linear1.bias
(2,)
encoder.layers.0.linear2.weight
(3, 2)
encoder.layers.0.linear2.bias
(3,)
encoder.layers.0.norm1.weight
(3,)
encoder.layers.0.norm1.bias
(3,)
encoder.layers.0.norm2.weight
(3,)
encoder.layers.0.norm2.bias
(3,)
encoder.layers.1.self_attn.in_proj_weight
(9, 3)
encoder.layers.1.self_attn.in_proj_bias
(9,)
encoder.layers.1.self_attn.out_proj.weight
(3, 3)
encoder.layers.1.self_attn.out_proj.bias
(3,)
encoder.layers.1.linear1.weight
(2, 3)
encoder.layers.1.linear1.bias
(2,)
encoder.layers.1.linear2.weight
(3, 2)
encoder.layers.1.linear2.bias
(3,)
encoder.layers.1.norm1.weight
(3,)
encoder.layers.1.norm1.bias
(3,)
encoder.layers.1.norm2.weight
(3,)
encoder.layers.1.norm2.bias
(3,)
head.weigh

In [9]:
import torch
import numpy as np

def tensor_to_points(name, t, num_heads=3, d_model=3):
    """
    Convert a tensor into points of shape (n, 3).
    Handles:
      - pos_emb (1, seq, 3)
      - embedding weights (vocab, 3)
      - linear weights (out, in)
      - biases (n,)
      - MultiheadAttention QKV weights (9, 3) → per-head Q/K/V points
      - MultiheadAttention QKV bias (9,) → per-head Q/K/V points
    """
    t = t.detach().cpu()

    # --- special case: MultiheadAttention QKV weights ---
    if "in_proj_weight" in name:
        # shape = (3 * d_model, d_model) = (9, 3)
        assert t.shape == (3 * d_model, d_model)

        # split Q, K, V along rows
        Wq, Wk, Wv = t.chunk(3, dim=0)    # each (3, 3)

        head_dim = d_model // num_heads   # here = 1

        # reshape to (num_heads, head_dim, d_model) = (3, 1, 3)
        Wq_h = Wq.view(num_heads, head_dim, d_model)
        Wk_h = Wk.view(num_heads, head_dim, d_model)
        Wv_h = Wv.view(num_heads, head_dim, d_model)

        out = {}
        for h in range(num_heads):
            out[f"{name}.Q.head{h}"] = Wq_h[h].numpy()   # (1,3)
            out[f"{name}.K.head{h}"] = Wk_h[h].numpy()   # (1,3)
            out[f"{name}.V.head{h}"] = Wv_h[h].numpy()   # (1,3)
        return out

    # --- special case: MultiheadAttention QKV bias ---
    if "in_proj_bias" in name:
        # shape = (9,)
        assert t.shape == (3 * d_model,)
        bq, bk, bv = t.chunk(3, dim=0)    # each (3,)
        out = {}
        for part_name, vec in zip(["Q", "K", "V"], [bq, bk, bv]):
            # reshape each bias vector (3,) as (3,1) then broadcast to (3,3)
            # so each element becomes a separate 3D point
            pts = vec.view(-1, 1).expand(-1, 3)
            out[f"{name}.{part_name}"] = pts.numpy()     # (3,3)
        return out

    # --- normal 3D-shaped positional embeddings ---
    if t.ndim == 3:
        # expect (1, seq, 3)
        assert t.shape[-1] == 3
        return {name: t.reshape(-1, 3).numpy()}

    # --- 2D matrices: weights ---
    if t.ndim == 2:
        out_dim, in_dim = t.shape
        if in_dim == 3:
            # each row is a 3D vector → (out_dim, 3)
            return {name: t.numpy()}
        elif out_dim == 3:
            # transpose so rows become 3D
            return {name: t.T.numpy()}
        else:
            # flatten weird shapes into 3D by grouping triples
            flat = t.flatten()
            n = flat.numel() // 3
            return {name: flat[:3*n].view(n, 3).numpy()}

    # --- 1D tensors: biases or norm weights ---
    if t.ndim == 1:
        if t.numel() == 3:
            # (3,) → (1,3)
            return {name: t.view(1,3).numpy()}
        else:
            # turn N numbers into N 3D points by repeating each scalar 3 times
            pts = t.view(-1, 1).expand(-1, 3)   # (N,3)
            return {name: pts.numpy()}

    raise ValueError(f"Don't know how to convert tensor {name} with shape {t.shape}")


def extract_all_points(model, num_heads=3, d_model=3):
    """
    Walks every named parameter and buffer in the model,
    converting them to 3D point clouds.
    """
    results = {}

    # named parameters
    for name, p in model.named_parameters():
        out = tensor_to_points(name, p, num_heads=num_heads, d_model=d_model)
        results.update(out)

    # named buffers (e.g. pos_emb)
    for name, b in model.named_buffers():
        out = tensor_to_points(name, b, num_heads=num_heads, d_model=d_model)
        results.update(out)

    return results


In [38]:
all_pts_model = extract_all_points(model, num_heads=model.nhead, d_model=model.d_model)
all_pts_base_model = extract_all_points(base_model, num_heads=base_model.nhead, d_model=base_model.d_model) 
for key in all_pts_model.keys():
    print(f"{key}: model pts={all_pts_model[key].shape}, base_model pts={all_pts_base_model[key].shape}")

for layer in model.named_parameters():
    print(layer[0], layer[1].detach().cpu().numpy().shape)

pos_emb: model pts=(8, 3), base_model pts=(8, 3)
embedding.weight: model pts=(6, 3), base_model pts=(6, 3)
encoder.layers.0.self_attn.in_proj_weight.Q.head0: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.K.head0: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.V.head0: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.Q.head1: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.K.head1: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.V.head1: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.Q.head2: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.K.head2: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_weight.V.head2: model pts=(1, 3), base_model pts=(1, 3)
encoder.layers.0.self_attn.in_proj_bias.Q: model pts=(3, 3), base_model pt

In [37]:
'''
for pt in all_pts_base_model.keys():
    print(pt, all_pts_base_model[pt].shape)
    print((all_pts_base_model[pt] - all_pts_model[pt]))
'''
    
pt = 'head.'  # change this to visualize other parts of the model

if 'encoder' or 'head' in pt:
    pts_base = np.array([[]])
    pts = np.array([[]])
    for key in all_pts_model.keys():
        if pt in key:
            print(pts_base)
            if pts_base.size == 0:
                pts_base = all_pts_base_model[key]
                pts = all_pts_model[key]
                labels_base = [key[len(pt):] + '0']
                labels = [key[len(pt):] + '0']
                for i in range(all_pts_base_model[key].shape[0] - 1):
                    labels_base.append(key[len(pt):] + str(i + 1))
                    labels.append(key[len(pt):] + str(i + 1))
            else:
                pts_base = np.append(pts_base, all_pts_base_model[key], axis=0)
                pts = np.append(pts, all_pts_model[key], axis=0)
                print(pts_base.shape)
                for i in range(all_pts_base_model[key].shape[0]):
                    labels_base.append(key[len(pt):] + str(i))
                    labels.append(key[len(pt):] + str(i))
            print(pts_base)
else:
    pts_base = all_pts_base_model[pt]
    pts = all_pts_model[pt]
    labels_base = [str(i) for i in range(len(pts_base))]
    labels = [str(i) for i in range(len(pts))]
print(pts_base.shape)
print(labels)
plot_3d_points(pts_base, labels=labels_base, show_labels_as_text=True, marker_size=8, renderer='notebook_connected')   
plot_3d_points(pts, labels=labels, show_labels_as_text=True, marker_size=8, renderer='notebook_connected')

[]
[[ 1.2978913   0.77315223 -0.46048418]
 [-1.0961275   1.5237862  -0.35797852]
 [-0.31867623 -1.1218554   0.9555952 ]
 [-0.20730558 -0.9290279   1.0864348 ]
 [-0.71706647 -1.4376966   0.59803325]
 [-0.56169474  0.3174633   0.7844257 ]]
[[ 1.2978913   0.77315223 -0.46048418]
 [-1.0961275   1.5237862  -0.35797852]
 [-0.31867623 -1.1218554   0.9555952 ]
 [-0.20730558 -0.9290279   1.0864348 ]
 [-0.71706647 -1.4376966   0.59803325]
 [-0.56169474  0.3174633   0.7844257 ]]
(12, 3)
[[ 1.2978913   0.77315223 -0.46048418]
 [-1.0961275   1.5237862  -0.35797852]
 [-0.31867623 -1.1218554   0.9555952 ]
 [-0.20730558 -0.9290279   1.0864348 ]
 [-0.71706647 -1.4376966   0.59803325]
 [-0.56169474  0.3174633   0.7844257 ]
 [ 0.3175949   0.3175949   0.3175949 ]
 [ 0.46366155  0.46366155  0.46366155]
 [ 0.00154167  0.00154167  0.00154167]
 [ 0.26301378  0.26301378  0.26301378]
 [ 0.00249871  0.00249871  0.00249871]
 [-0.36047423 -0.36047423 -0.36047423]]
(12, 3)
['weight0', 'weight1', 'weight2', 'weight3